"""Initial schema.

Revision ID: cfc5eda15287
Revises:
Create Date: 2026-08-16 23:52:52.908435
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "cfc5eda15287"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commission_statuses',
    sa.Column('id', sa.SmallInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='commission_statuses_code_key'),
    sa.UniqueConstraint('name', name='commission_statuses_name_key')
    )
    op.create_table('fuel_coupons',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('coupon_number', sa.String(length=50), nullable=False),
    sa.Column('face_value_q', sa.Numeric(precision=10, scale=2), server_default=sa.text('100.00'), nullable=False, comment='Actualmente los cupones son de Q100. No se restringe a exactamente Q100 para no bloquear un cambio institucional futuro.'),
    sa.Column('coupon_date', sa.Date(), nullable=True),
    sa.Column('gas_station', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('face_value_q > 0', name='ck_fuel_coupons_face_value'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coupon_number')
    )
    op.create_table('roles',
    sa.Column('id', sa.SmallInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='roles_code_key'),
    sa.UniqueConstraint('name', name='roles_name_key')
    )
    op.create_table('service_types',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('interval_km', sa.Numeric(precision=12, scale=1), nullable=True),
    sa.Column('interval_days', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('interval_days IS NULL OR interval_days > 0', name='ck_service_types_interval_days'),
    sa.CheckConstraint('interval_km IS NULL OR interval_km > 0', name='ck_service_types_interval_km'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='PENDIENTE DE CONFIRMACIÓN: determinar si la periodicidad de servicios se controla por kilometraje, tiempo o ambos. La V1 soporta las tres posibilidades sin obligar ninguna.'
    )
    op.create_table('vehicles',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('inventory_code', sa.String(length=50), nullable=False),
    sa.Column('license_plate', sa.String(length=20), nullable=False),
    sa.Column('brand', sa.String(length=80), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('vehicle_type', sa.String(length=80), nullable=False),
    sa.Column('fuel_type', sa.String(length=30), nullable=False),
    sa.Column('current_odometer_km', sa.Numeric(precision=12, scale=1), server_default='0', nullable=False),
    sa.Column('tank_capacity_gal', sa.Numeric(precision=8, scale=3), nullable=True, comment='PENDIENTE DE CONFIRMACIÓN: capacidad del tanque en galones. Se deja nullable para soportar el cálculo futuro de combustible restante sin inventar valores.'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('current_odometer_km >= 0', name='ck_vehicles_odometer'),
    sa.CheckConstraint('tank_capacity_gal IS NULL OR tank_capacity_gal > 0', name='ck_vehicles_tank_capacity'),
    sa.CheckConstraint('year >= 1900', name='ck_vehicles_year'),
    sa.PrimaryKeyConstraint('id'),
    comment='Cilindraje/C.C. no se agregan todavía porque falta confirmar si representan el mismo dato o datos diferentes.'
    )
    op.create_index('uq_vehicles_inventory_code_ci', 'vehicles', [sa.literal_column('lower(inventory_code)')], unique=True)
    op.create_index('uq_vehicles_license_plate_ci', 'vehicles', [sa.literal_column('lower(license_plate)')], unique=True)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('role_id', sa.SmallInteger(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('institutional_email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('position', sa.String(length=100), nullable=False),
    sa.Column('area_department', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='fk_users_role', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_users_role_id', 'users', ['role_id'], unique=False)
    op.create_index('uq_users_institutional_email_ci', 'users', [sa.literal_column('lower(institutional_email)')], unique=True)
    op.create_table('commissions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('requester_user_id', sa.BigInteger(), nullable=False),
    sa.Column('vehicle_id', sa.BigInteger(), nullable=True),
    sa.Column('status_id', sa.SmallInteger(), nullable=False),
    sa.Column('scheduled_start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('scheduled_end_at > scheduled_start_at', name='ck_commissions_schedule'),
    sa.ForeignKeyConstraint(['requester_user_id'], ['users.id'], name='fk_commissions_requester', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], name='fk_commissions_reviewer', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['status_id'], ['commission_statuses.id'], name='fk_commissions_status', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name='fk_commissions_vehicle', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='Las comisiones rechazadas o canceladas permanecen almacenadas. No deben representarse mediante DELETE físico.'
    )
    op.create_index('idx_commissions_requester', 'commissions', ['requester_user_id'], unique=False)
    op.create_index('idx_commissions_status', 'commissions', ['status_id'], unique=False)
    op.create_index('idx_commissions_vehicle_schedule', 'commissions', ['vehicle_id', 'scheduled_start_at', 'scheduled_end_at'], unique=False, postgresql_where=sa.text('vehicle_id IS NOT NULL'))
    op.create_table('maintenance_events',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('vehicle_id', sa.BigInteger(), nullable=False),
    sa.Column('maintenance_type', sa.String(length=20), nullable=False),
    sa.Column('maintenance_date', sa.Date(), nullable=False),
    sa.Column('odometer_km', sa.Numeric(precision=12, scale=1), nullable=True),
    sa.Column('workshop', sa.String(length=150), nullable=True),
    sa.Column('cost_q', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('next_maintenance_date', sa.Date(), nullable=True),
    sa.Column('next_maintenance_odometer_km', sa.Numeric(precision=12, scale=1), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_user_id', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("maintenance_type IN ('PREVENTIVO', 'CORRECTIVO')", name='ck_maintenance_events_type'),
    sa.CheckConstraint('odometer_km IS NULL OR odometer_km >= 0', name='ck_maintenance_events_odometer'),
    sa.ForeignKeyConstraint(['deleted_by_user_id'], ['users.id'], name='fk_maintenance_events_deleted_by', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_maintenance_events_vehicle_date', 'maintenance_events', ['vehicle_id', 'maintenance_date'], unique=False)
    op.create_table('commission_coupons',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('commission_id', sa.BigInteger(), nullable=False),
    sa.Column('coupon_id', sa.BigInteger(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('returned_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('NOT (used_at IS NOT NULL AND returned_at IS NOT NULL)', name='ck_commission_coupons_not_used_and_returned'),
    sa.CheckConstraint('returned_at IS NULL OR returned_at >= assigned_at', name='ck_commission_coupons_returned_after_assignment'),
    sa.CheckConstraint('used_at IS NULL OR used_at >= assigned_at', name='ck_commission_coupons_used_after_assignment'),
    sa.ForeignKeyConstraint(['commission_id'], ['commissions.id'], name='fk_commission_coupons_commission', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['coupon_id'], ['fuel_coupons.id'], name='fk_commission_coupons_coupon', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='Cuando un cupón se devuelve, la relación histórica se conserva con returned_at, aunque funcionalmente deje de mostrarse como asignado a la comisión.'
    )
    op.create_index('idx_commission_coupons_commission', 'commission_coupons', ['commission_id'], unique=False)
    op.create_index('idx_commission_coupons_coupon', 'commission_coupons', ['coupon_id'], unique=False)
    op.create_index('uq_commission_coupons_active_coupon', 'commission_coupons', ['coupon_id'], unique=True, postgresql_where=sa.text('returned_at IS NULL'))
    op.create_table('fuel_loads',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('commission_id', sa.BigInteger(), nullable=False),
    sa.Column('loaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gas_station', sa.String(length=150), nullable=False),
    sa.Column('gallons', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('amount_q', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount_q > 0', name='ck_fuel_loads_amount'),
    sa.CheckConstraint('gallons > 0', name='ck_fuel_loads_gallons'),
    sa.ForeignKeyConstraint(['commission_id'], ['commissions.id'], name='fk_fuel_loads_commission', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='Separa el dinero/cupones asignados del combustible realmente cargado. Permite calcular galones y gasto para el dashboard.'
    )
    op.create_index('idx_fuel_loads_commission', 'fuel_loads', ['commission_id'], unique=False)
    op.create_index('idx_fuel_loads_loaded_at', 'fuel_loads', ['loaded_at'], unique=False)
    op.create_table('maintenance_event_services',
    sa.Column('maintenance_event_id', sa.BigInteger(), nullable=False),
    sa.Column('service_type_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['maintenance_event_id'], ['maintenance_events.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['service_type_id'], ['service_types.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('maintenance_event_id', 'service_type_id')
    )
    op.create_index('idx_maintenance_event_services_service', 'maintenance_event_services', ['service_type_id'], unique=False)
    op.create_table('maintenance_parts',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('maintenance_event_id', sa.BigInteger(), nullable=False),
    sa.Column('part_name', sa.String(length=150), nullable=False),
    sa.Column('quantity', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_maintenance_parts_quantity'),
    sa.ForeignKeyConstraint(['maintenance_event_id'], ['maintenance_events.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_maintenance_parts_event', 'maintenance_parts', ['maintenance_event_id'], unique=False)
    op.create_table('trips',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('commission_id', sa.BigInteger(), nullable=False),
    sa.Column('driver_user_id', sa.BigInteger(), nullable=False),
    sa.Column('sequence_number', sa.SmallInteger(), nullable=False),
    sa.Column('trip_date', sa.Date(), nullable=False),
    sa.Column('origin', sa.String(length=200), nullable=False),
    sa.Column('destination', sa.String(length=200), nullable=False),
    sa.Column('odometer_start_km', sa.Numeric(precision=12, scale=1), nullable=False),
    sa.Column('odometer_end_km', sa.Numeric(precision=12, scale=1), nullable=False),
    sa.Column('distance_km', sa.Numeric(precision=12, scale=1), sa.Computed('odometer_end_km - odometer_start_km', persisted=True), nullable=True),
    sa.Column('tank_balance_percent', sa.Numeric(precision=5, scale=2), nullable=True, comment='Porcentaje estimado de combustible restante. La equivalencia exacta del valor E del formato actual sigue pendiente de confirmación.'),
    sa.Column('road_type', sa.CHAR(length=1), nullable=False, comment='A = Asfalto, T = Tierra.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_user_id', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("road_type IN ('A', 'T')", name='ck_trips_road_type'),
    sa.CheckConstraint('odometer_end_km >= odometer_start_km', name='ck_trips_odometer_order'),
    sa.CheckConstraint('odometer_start_km >= 0', name='ck_trips_odometer_start'),
    sa.CheckConstraint('sequence_number > 0', name='ck_trips_sequence'),
    sa.CheckConstraint('tank_balance_percent IS NULL OR tank_balance_percent BETWEEN 0 AND 100', name='ck_trips_tank_balance'),
    sa.ForeignKeyConstraint(['commission_id'], ['commissions.id'], name='fk_trips_commission', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by_user_id'], ['users.id'], name='fk_trips_deleted_by', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['driver_user_id'], ['users.id'], name='fk_trips_driver', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('commission_id', 'sequence_number', name='uq_trips_commission_sequence')
    )
    op.create_index('idx_trips_commission', 'trips', ['commission_id'], unique=False)
    op.create_index('idx_trips_date', 'trips', ['trip_date'], unique=False)
    op.create_index('idx_trips_driver', 'trips', ['driver_user_id'], unique=False)

    # --- SIGVE seed catalogs ---
    op.execute(
        """
        INSERT INTO roles (code, name)
        VALUES
            ('ADMINISTRATION', 'Administraci?n'),
            ('COLLABORATOR', 'Colaborador')
        """
    )

    op.execute(
        """
        INSERT INTO commission_statuses (code, name)
        VALUES
            ('PENDING', 'Pendiente'),
            ('APPROVED', 'Aprobada'),
            ('REJECTED', 'Rechazada'),
            ('CANCELLED', 'Cancelada')
        """
    )

    # --- SIGVE PostgreSQL functions ---
    op.execute(
        """
        CREATE OR REPLACE FUNCTION public.prevent_approved_vehicle_overlap()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $function$
        DECLARE
            new_status_code VARCHAR(30);
        BEGIN
            IF NEW.vehicle_id IS NULL THEN
                RETURN NEW;
            END IF;

            SELECT code
              INTO new_status_code
              FROM commission_statuses
             WHERE id = NEW.status_id;

            IF new_status_code <> 'APPROVED' THEN
                RETURN NEW;
            END IF;

            -- Serializa validaciones concurrentes para el mismo veh?culo.
            PERFORM pg_advisory_xact_lock(NEW.vehicle_id);

            IF EXISTS (
                SELECT 1
                  FROM commissions c
                  JOIN commission_statuses cs
                    ON cs.id = c.status_id
                 WHERE c.vehicle_id = NEW.vehicle_id
                   AND c.id <> COALESCE(NEW.id, 0)
                   AND cs.code = 'APPROVED'
                   AND tstzrange(
                           c.scheduled_start_at,
                           c.scheduled_end_at,
                           '[)'
                       )
                       &&
                       tstzrange(
                           NEW.scheduled_start_at,
                           NEW.scheduled_end_at,
                           '[)'
                       )
            ) THEN
                RAISE EXCEPTION
                    'El veh?culo % ya est? asignado a otra comisi?n aprobada dentro del intervalo solicitado.',
                    NEW.vehicle_id
                    USING ERRCODE = '23P01';
            END IF;

            RETURN NEW;
        END;
        $function$;
        """
    )

    op.execute(
        """
        CREATE OR REPLACE FUNCTION public.set_updated_at()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $function$
        BEGIN
            NEW.updated_at = NOW();
            RETURN NEW;
        END;
        $function$;
        """
    )

    # --- SIGVE triggers ---
    op.execute(
        """
        CREATE TRIGGER trg_commissions_prevent_vehicle_overlap
        BEFORE INSERT OR UPDATE OF
            vehicle_id,
            status_id,
            scheduled_start_at,
            scheduled_end_at
        ON commissions
        FOR EACH ROW
        EXECUTE FUNCTION prevent_approved_vehicle_overlap()
        """
    )

    op.execute(
        """
        CREATE TRIGGER trg_commissions_updated_at
        BEFORE UPDATE ON commissions
        FOR EACH ROW
        EXECUTE FUNCTION set_updated_at()
        """
    )

    op.execute(
        """
        CREATE TRIGGER trg_users_updated_at
        BEFORE UPDATE ON users
        FOR EACH ROW
        EXECUTE FUNCTION set_updated_at()
        """
    )

    op.execute(
        """
        CREATE TRIGGER trg_vehicles_updated_at
        BEFORE UPDATE ON vehicles
        FOR EACH ROW
        EXECUTE FUNCTION set_updated_at()
        """
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # --- SIGVE triggers/functions ---
    op.execute(
        "DROP TRIGGER IF EXISTS trg_commissions_prevent_vehicle_overlap "
        "ON commissions"
    )
    op.execute(
        "DROP TRIGGER IF EXISTS trg_commissions_updated_at ON commissions"
    )
    op.execute(
        "DROP TRIGGER IF EXISTS trg_users_updated_at ON users"
    )
    op.execute(
        "DROP TRIGGER IF EXISTS trg_vehicles_updated_at ON vehicles"
    )

    op.execute(
        "DROP FUNCTION IF EXISTS public.prevent_approved_vehicle_overlap()"
    )
    op.execute(
        "DROP FUNCTION IF EXISTS public.set_updated_at()"
    )

    op.drop_index('idx_trips_driver', table_name='trips')
    op.drop_index('idx_trips_date', table_name='trips')
    op.drop_index('idx_trips_commission', table_name='trips')
    op.drop_table('trips')
    op.drop_index('idx_maintenance_parts_event', table_name='maintenance_parts')
    op.drop_table('maintenance_parts')
    op.drop_index('idx_maintenance_event_services_service', table_name='maintenance_event_services')
    op.drop_table('maintenance_event_services')
    op.drop_index('idx_fuel_loads_loaded_at', table_name='fuel_loads')
    op.drop_index('idx_fuel_loads_commission', table_name='fuel_loads')
    op.drop_table('fuel_loads')
    op.drop_index('uq_commission_coupons_active_coupon', table_name='commission_coupons', postgresql_where=sa.text('returned_at IS NULL'))
    op.drop_index('idx_commission_coupons_coupon', table_name='commission_coupons')
    op.drop_index('idx_commission_coupons_commission', table_name='commission_coupons')
    op.drop_table('commission_coupons')
    op.drop_index('idx_maintenance_events_vehicle_date', table_name='maintenance_events')
    op.drop_table('maintenance_events')
    op.drop_index('idx_commissions_vehicle_schedule', table_name='commissions', postgresql_where=sa.text('vehicle_id IS NOT NULL'))
    op.drop_index('idx_commissions_status', table_name='commissions')
    op.drop_index('idx_commissions_requester', table_name='commissions')
    op.drop_table('commissions')
    op.drop_index('uq_users_institutional_email_ci', table_name='users')
    op.drop_index('idx_users_role_id', table_name='users')
    op.drop_table('users')
    op.drop_index('uq_vehicles_license_plate_ci', table_name='vehicles')
    op.drop_index('uq_vehicles_inventory_code_ci', table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_table('service_types')
    op.drop_table('roles')
    op.drop_table('fuel_coupons')
    op.drop_table('commission_statuses')
    # ### end Alembic commands ###
